# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paste.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
#          run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EmailSlicer(object):
    def setupUi(self, EmailSlicer):
        EmailSlicer.setObjectName("EmailSlicer")
        EmailSlicer.resize(1008, 580)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(EmailSlicer)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        
        # Left Main Layout
        self.Left_Main = QtWidgets.QVBoxLayout()
        self.Left_Main.setObjectName("Left_Main")
        
        # Title Label
        self.titleLabel = QtWidgets.QLabel(EmailSlicer)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(26)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.titleLabel.setMargin(10)
        self.titleLabel.setObjectName("titleLabel")
        self.Left_Main.addWidget(self.titleLabel)
        
        # Input Group
        self.inputGroup = QtWidgets.QGroupBox(EmailSlicer)
        self.inputGroup.setObjectName("inputGroup")
        self.formLayout = QtWidgets.QFormLayout(self.inputGroup)
        self.formLayout.setObjectName("formLayout")
        
        self.emailLabel = QtWidgets.QLabel(self.inputGroup)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.emailLabel)
        
        self.email_input = QtWidgets.QLineEdit(self.inputGroup)
        self.email_input.setObjectName("email_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.email_input)
        
        self.Left_Main.addWidget(self.inputGroup)
        
        # Action Group
        self.actionGroup = QtWidgets.QGroupBox(EmailSlicer)
        self.actionGroup.setObjectName("actionGroup")
        self.buttonLayout = QtWidgets.QGridLayout(self.actionGroup)
        self.buttonLayout.setObjectName("buttonLayout")
        
        self.slice_button = QtWidgets.QPushButton(self.actionGroup)
        self.slice_button.setObjectName("slice_button")
        self.buttonLayout.addWidget(self.slice_button, 0, 0, 1, 1)
        
        self.load_db_button = QtWidgets.QPushButton(self.actionGroup)
        self.load_db_button.setObjectName("load_db_button")
        self.buttonLayout.addWidget(self.load_db_button, 0, 1, 1, 1)
        
        self.load_file_button = QtWidgets.QPushButton(self.actionGroup)
        self.load_file_button.setObjectName("load_file_button")
        self.buttonLayout.addWidget(self.load_file_button, 0, 2, 1, 1)
        
        self.save_temp_file_button = QtWidgets.QPushButton(self.actionGroup)
        self.save_temp_file_button.setObjectName("save_temp_file_button")
        self.buttonLayout.addWidget(self.save_temp_file_button, 1, 0, 1, 1)
        
        self.save_db_file_button = QtWidgets.QPushButton(self.actionGroup)
        self.save_db_file_button.setObjectName("save_db_file_button")
        self.buttonLayout.addWidget(self.save_db_file_button, 1, 1, 1, 1)
        
        self.save_db_button = QtWidgets.QPushButton(self.actionGroup)
        self.save_db_button.setObjectName("save_db_button")
        self.buttonLayout.addWidget(self.save_db_button, 1, 2, 1, 1)
        
        self.search_user_button = QtWidgets.QPushButton(self.actionGroup)
        self.search_user_button.setObjectName("search_user_button")
        self.buttonLayout.addWidget(self.search_user_button, 2, 0, 1, 3)
        
        self.Left_Main.addWidget(self.actionGroup)
        
        # Table Group
        self.tableGroup = QtWidgets.QGroupBox(EmailSlicer)
        self.tableGroup.setObjectName("tableGroup")
        self.tableLayout = QtWidgets.QVBoxLayout(self.tableGroup)
        self.tableLayout.setObjectName("tableLayout")
        
        self.email_temp_table = QtWidgets.QTableWidget(self.tableGroup)
        self.email_temp_table.setRowCount(0)
        self.email_temp_table.setColumnCount(3)
        self.email_temp_table.setObjectName("email_temp_table")
        
        item = QtWidgets.QTableWidgetItem()
        self.email_temp_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.email_temp_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.email_temp_table.setHorizontalHeaderItem(2, item)
        
        self.tableLayout.addWidget(self.email_temp_table)
        self.Left_Main.addWidget(self.tableGroup)
        
        self.horizontalLayout_3.addLayout(self.Left_Main)
        
        # Right Main Layout
        self.Right_Main = QtWidgets.QVBoxLayout()
        self.Right_Main.setObjectName("Right_Main")
        
        # Database Group
        self.databaseGroup = QtWidgets.QGroupBox(EmailSlicer)
        self.databaseGroup.setObjectName("databaseGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.databaseGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.database_email_table = QtWidgets.QTableWidget(self.databaseGroup)
        self.database_email_table.setColumnCount(3)
        self.database_email_table.setObjectName("database_email_table")
        
        item = QtWidgets.QTableWidgetItem()
        self.database_email_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_email_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.database_email_table.setHorizontalHeaderItem(2, item)
        
        self.verticalLayout_2.addWidget(self.database_email_table)
        self.Right_Main.addWidget(self.databaseGroup)
        
        self.horizontalLayout_3.addLayout(self.Right_Main)
        
        # Set stretch factors for main layout (5:4 ratio as specified in UI)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 4)

        self.retranslateUi(EmailSlicer)
        QtCore.QMetaObject.connectSlotsByName(EmailSlicer)

    def retranslateUi(self, EmailSlicer):
        _translate = QtCore.QCoreApplication.translate
        EmailSlicer.setWindowTitle(_translate("EmailSlicer", "Email Slicer & Data Handling"))
        self.titleLabel.setText(_translate("EmailSlicer", "Email Slicer & Data Handler"))
        self.inputGroup.setTitle(_translate("EmailSlicer", "Input Section"))
        self.emailLabel.setText(_translate("EmailSlicer", "Email Address:"))
        self.email_input.setPlaceholderText(_translate("EmailSlicer", "Enter email address"))
        self.actionGroup.setTitle(_translate("EmailSlicer", "Actions"))
        self.slice_button.setText(_translate("EmailSlicer", "Slice Email"))
        self.load_db_button.setText(_translate("EmailSlicer", "Load from Database"))
        self.load_file_button.setText(_translate("EmailSlicer", "Load from File"))
        self.save_temp_file_button.setText(_translate("EmailSlicer", "Save temp data to CSV file"))
        self.save_db_file_button.setText(_translate("EmailSlicer", "Save DB data to CSV file"))
        self.save_db_button.setText(_translate("EmailSlicer", "Save to Database"))
        self.search_user_button.setText(_translate("EmailSlicer", "Search Database By Username"))
        self.tableGroup.setTitle(_translate("EmailSlicer", "Sliced Emails (temporary)"))
        self.databaseGroup.setTitle(_translate("EmailSlicer", "Database"))
        
        # Set table headers
        self.email_temp_table.horizontalHeaderItem(0).setText(_translate("EmailSlicer", "Username"))
        self.email_temp_table.horizontalHeaderItem(1).setText(_translate("EmailSlicer", "Domain"))
        self.email_temp_table.horizontalHeaderItem(2).setText(_translate("EmailSlicer", "Extension"))
        
        self.database_email_table.horizontalHeaderItem(0).setText(_translate("EmailSlicer", "Username"))
        self.database_email_table.horizontalHeaderItem(1).setText(_translate("EmailSlicer", "Domain"))
        self.database_email_table.horizontalHeaderItem(2).setText(_translate("EmailSlicer", "Extension"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EmailSlicer = QtWidgets.QWidget()
    ui = Ui_EmailSlicer()
    ui.setupUi(EmailSlicer)
    EmailSlicer.show()
    sys.exit(app.exec_())